version: '2'

services:
    nginx:
        image: nginx
        links:
            - app
        volumes:
            - ./SparkSchoolCourses/_site:/site
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/nginx/ssl/trysparkschool.crt:/etc/nginx/ssl/trysparkschool.crt
            - /etc/nginx/ssl/trysparkschool.key:/etc/nginx/ssl/trysparkschool.key
        ports:
            - 80:80
            - 443:443
    app:
        build: ./app
        env_file:
            - ./app/vars.env
